server:
  port: 8080
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
#  jackson:
#    time-zone: "GMT+8"
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sfdb?serverTimezone=Asia/Shanghai
    username: root
    password: jueshi123

#    tuo feng -> xia hua xian
mybatis:
  configuration:
    map-underscore-to-camel-case: true
